export const COMM_DATA = [
  {
    transaction_date: "2026-02-09",
    counterparty: "통신요금",
    amount: 9540,
    supply_value: 8673,
    vat_amount: 867,
    proof_type: "신용카드" as const,
    memo: "통신비 / 사업용 휴대폰 요금",
  },
  {
    transaction_date: "2026-03-09",
    counterparty: "통신요금",
    amount: 3890,
    supply_value: 3536,
    vat_amount: 354,
    proof_type: "신용카드" as const,
    memo: "통신비 / 사업용 휴대폰 요금",
  },
  {
    transaction_date: "2026-04-09",
    counterparty: "통신요금",
    amount: 3890,
    supply_value: 3536,
    vat_amount: 354,
    proof_type: "신용카드" as const,
    memo: "통신비 / 사업용 휴대폰 요금",
  },
  {
    transaction_date: "2026-05-09",
    counterparty: "통신요금",
    amount: 3890,
    supply_value: 3536,
    vat_amount: 354,
    proof_type: "신용카드" as const,
    memo: "통신비 / 사업용 휴대폰 요금",
  },
  {
    transaction_date: "2026-06-09",
    counterparty: "통신요금",
    amount: 3890,
    supply_value: 3536,
    vat_amount: 354,
    proof_type: "신용카드" as const,
    memo: "통신비 / 사업용 휴대폰 요금",
  },
];
