export const IMPORT_DATA = [
  {
    transaction_date: "2025-12-29",
    counterparty: "구글",
    amount: 140000,
    supply_value: 127273,
    vat_amount: 12727,
    proof_type: "신용카드" as const,
    memo: "소프트웨어 사용료 / 사업 운영 중 생성되는 업무용 구글 서비스",
  },
  {
    transaction_date: "2026-01-09",
    counterparty: "애플",
    amount: 1840000,
    supply_value: 1672727,
    vat_amount: 167273,
    proof_type: "신용카드" as const,
    memo: "비품 / 소프트웨어 개발용 메인 PC",
  },
  {
    transaction_date: "2026-01-05",
    counterparty: "통신판매업 등록면허세",
    amount: 40500,
    supply_value: 0,
    vat_amount: 0,
    proof_type: "영수증없음" as const,
    memo: "세금과공과 / 통신판매업 등록면허세",
  },
  {
    transaction_date: "2026-01-26",
    counterparty: "가비아",
    amount: 16500,
    supply_value: 15000,
    vat_amount: 1500,
    proof_type: "신용카드" as const,
    memo: "소프트웨어 사용료 / 도메인 구입비용",
  },
  {
    transaction_date: "2026-01-26",
    counterparty: "엔산마운트",
    amount: 407500,
    supply_value: 370455,
    vat_amount: 37045,
    proof_type: "신용카드" as const,
    memo: "사무용품/소모품비 / 소프트웨어 개발 업무용 데스크 장비",
  },
  {
    transaction_date: "2026-01-26",
    counterparty: "가비아",
    amount: 16500,
    supply_value: 15000,
    vat_amount: 1500,
    proof_type: "신용카드" as const,
    memo: "소프트웨어 사용료 / 자사 웹 서비스 배포 및 운영",
  },
  {
    transaction_date: "2026-02-05",
    counterparty: "Logomaster.ai",
    amount: 25415,
    supply_value: 25415,
    vat_amount: 0,
    proof_type: "신용카드" as const,
    memo: "광고선전비 / 자사 서비스 브랜드 아이덴티티",
  },
  {
    transaction_date: "2026-06-18",
    counterparty: "Anthropic - claude ai",
    amount: 20,
    supply_value: 20,
    vat_amount: 0,
    proof_type: "신용카드" as const,
    memo: "소프트웨어 사용료 / 소프트웨어 개발 및 서비스 (USD $20)",
  },
  {
    transaction_date: "2026-05-18",
    counterparty: "Anthropic - claude ai",
    amount: 20,
    supply_value: 20,
    vat_amount: 0,
    proof_type: "신용카드" as const,
    memo: "소프트웨어 사용료 / 소프트웨어 개발 및 서비스 (USD $20)",
  },
  {
    transaction_date: "2026-05-22",
    counterparty: "Supabase",
    amount: 25,
    supply_value: 25,
    vat_amount: 0,
    proof_type: "신용카드" as const,
    memo: "소프트웨어 사용료 / 비위더스 DB 사용료 (USD $25)",
  },
];
